import {
  siApachekafka,
  siCplusplus,
  siDocker,
  siElasticsearch,
  siFastapi,
  siGo,
  siHuggingface,
  siJavascript,
  siKubernetes,
  siLangchain,
  siLanggraph,
  siModelcontextprotocol,
  siMongodb,
  siNeo4j,
  siNodedotjs,
  siOpencv,
  siPostgresql,
  siPython,
  siPytorch,
  siReact,
  siRust,
  siScikitlearn,
  siSpringboot,
  siTensorflow,
  siTerraform,
  siTypescript,
} from "simple-icons";

export const skillIcons = {
  apachekafka: siApachekafka,
  cplusplus: siCplusplus,
  docker: siDocker,
  elasticsearch: siElasticsearch,
  fastapi: siFastapi,
  go: siGo,
  huggingface: siHuggingface,
  javascript: siJavascript,
  kubernetes: siKubernetes,
  langchain: siLangchain,
  langgraph: siLanggraph,
  modelcontextprotocol: siModelcontextprotocol,
  mongodb: siMongodb,
  neo4j: siNeo4j,
  nodedotjs: siNodedotjs,
  opencv: siOpencv,
  postgresql: siPostgresql,
  python: siPython,
  pytorch: siPytorch,
  react: siReact,
  rust: siRust,
  scikitlearn: siScikitlearn,
  springboot: siSpringboot,
  tensorflow: siTensorflow,
  terraform: siTerraform,
  typescript: siTypescript,
};
